FROM python:3

RUN mkdir /workspace
WORKDIR /workspace

COPY galactic_router galactic_router
COPY features features
COPY .flake8 .flake8
COPY pyproject.toml .

RUN pip install -e .[test]
RUN flake8 -v .
RUN behave
