"""Add created field to registration table

Revision ID: 042d8775f6e0
Revises: 0e50c4ae5859
Create Date: 2025-09-30 23:41:19.997847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '042d8775f6e0'
down_revision: Union[str, Sequence[str], None] = '0e50c4ae5859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'created')
    # ### end Alembic commands ###
