"""Init

Revision ID: 0e50c4ae5859
Revises: 
Create Date: 2025-09-30 23:27:48.597491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e50c4ae5859'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vpc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_vpc'), 'registration', ['vpc'], unique=False)
    op.create_index('ix_registration_vpc_network', 'registration', ['vpc', 'network'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registration_vpc_network', table_name='registration')
    op.drop_index(op.f('ix_registration_vpc'), table_name='registration')
    op.drop_table('registration')
    # ### end Alembic commands ###
