name: Publish Docker Image

on:
  # Trigger on push
  push:
  # Trigger on all pull requests
  pull_request:
  # Trigger when a release is published
  release:
    types: ['published']

jobs:
  publish-container-image:
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.5.1
    with:
      image-name: galactic-router
    secrets: inherit
